---
title: "Generate Most Frequent Combined Variables"
output: html_notebook
---

## A script to generate a limited set of combined variables for each file in the input directory.


```{r}

## This script generates a limited set of new varialbes for each file in the input directory.

library(XML)
library(tidyverse)
library(stringr)

most_frequent.list <- readRDS("most_freq_list.R")

var_names.v <- readRDS("variable_names.R")

input.dir <- "./output_2"

files.v <- dir(path=input.dir, pattern=".*xml")

list_of_working_tibbles <- vector(mode = "list", length(files.v))

for (i in seq_along(files.v)) {
  
  start_time <- Sys.time()
  print(start_time)
  
  # read xml structure from file to .R object
  doc.object <- xmlTreeParse(file.path(input.dir, files.v[i]), useInternalNodes=TRUE)
  
  # extract all <word> elements and children into XmlNodeList object
  word.nodes <- getNodeSet(doc.object, "//word")
  
  
  word.list <- xmlApply(word.nodes, xmlToList)
  
  
  
  
  for (j in seq_along(var_names.v)) {
    
    if ( j == 1) {
      
      base.df <- word.list %>% map_chr(var_names.v[j]) %>%
        data.frame(check.names = FALSE, stringsAsFactors = FALSE)
      
    } else {
      
      base.df <- word.list %>% map_chr(var_names.v[j]) %>%
        cbind(base.df,  ., stringsAsFactors = FALSE)
      
    }
    
  }
  
  colnames(base.df) <- var_names.v
  
  ###
  
  new_vars.m <- matrix(nrow = nrow(base.df), ncol = 1)
  nomina <- NULL
  
  for (k in seq_along(most_frequent.list)) {
    var_atoms <- most_frequent.list[[k]]
    if (length(var_atoms) > 1) {
      combined_var <- base.df[, var_atoms] %>%
        apply(., 1, paste0, collapse = "/")
      
    } else {
      combined_var <- base.df[, var_atoms]
      
    }
    new_vars.m <- cbind(new_vars.m, combined_var)
    
    nomina <- append(nomina, paste0(var_atoms, collapse = "_&_"))
  }
  
  
  new_vars.m <- new_vars.m[, -1]
  
  
  new_vars.m[str_detect(new_vars.m, "NA")] <- NA # add logical NA to cells
  
  
  new_vars.m[str_detect(new_vars.m, "NULL")] <- NA # add logical NA to cells
  
  new_vars.m <-tolower(new_vars.m)
  
  nomina <-  c("token_id", "cite", "form", nomina)
  
  
  file_name <- files.v[i] %>%
    gsub(".xml","", .)
  
  token_id <- seq_len(nrow(base.df)) %>%
    paste0(file_name, "_token_", .) 
  
  
  new_vars.m <- cbind(token_id, base.df[, "cite"], base.df[, "form"], new_vars.m)
  
  colnames(new_vars.m) <- nomina
  
  vars.tib <- as_tibble(new_vars.m)
  
  list_of_working_tibbles[[i]] <- vars.tib
  
  end_time <- Sys.time()
  print(paste("end of loop", i, files.v[i]))
  print(end_time - start_time)
  
  start_time <- Sys.time()
  print(paste("saving variables for", files.v[i]))
  saveRDS(list_of_working_tibbles, file = "all_files_comb_vars.R")
  end_time <- Sys.time()
  print(end_time - start_time)
  
  
} #end of main loop 




```






#### Notes on code details:

* **library(XML), library(tidyverse),** and **library(stringr)** load the packages necessary to run the code.
* **most_frequent.list <- readRDS("most_freq_list.R")** loads from disk a saved list object containing the combined variables which have been pre-selected for use. The data are stored in the list object called **most_frequent.list.**
  + **readRDS( )** takes as its argument the name of the file to load.
* **var_names.v <- readRDS("variable_names.R")** loads into a vector object the pre-saved names of the variables which will be used to extract the attributes of interest from the XML input files.
* **input.dir <- "./output_2"** stores the path for the directory containing the input XML files as a character vector.
* **files.v <- dir(path=input.dir, pattern=".&#42;xml")** creates a character vector containing the input files to be processed.
  + **dir( )** produces a character vector of the names of files or directories in the named directory.  The **path** argument is here set by the content of the vector object **input.dir**. The **pattern** argument uses regular expression syntax to match files to be included. Here **.&#42;xml** matches any file with the suffix "xml": the dot (.) matches any character and the asterisk (&#42;) matches the preceding character any number of times.
* **list_of_working_tibbles <- vector(mode = "list", length(files.v))** creates an empty list object with the number of list elements equal to the number of files to be processed. This list will store the results of the variable extraction and combination. 
* **for (i in seq_along(files.v)) { ... }** is a loop iterating for each file. The iteration is set by **seq_along(files.v)** for the number of elements in the **files.v** character vector.
  + **start_time <- Sys.time()** creates a vector with the time at which the loop starts processing. It will be used to keep track of progress.
  + **print(start_time)** prints the time on the screen so that it can be read while the loop is iterating. 
  + **doc.object <- xmlTreeParse(file.path(input.dir, files.v[i]), useInternalNodes=TRUE)** creates an object containing a  representation of the XML structure ot the input. **xmlTreeParse( )** is a function from the XML package. The argument **useInternalNodes** must be set to **TRUE** or the function does not work properly.
    + **file.path( )** creates a character vector of the input arguments separated by a forward slash character. Here **files.v[i]** specifies, according to the iteration of the for loop, the ith element in the list of the contents of the input directory.
  + **word.nodes <- getNodeSet(doc.object, "//word")** creates an object containing a representation of all word nodes in the input file. **getNodeSet( )** is a function from the XML package.  The first argument is the input XML object. The second argument is an XPath expression identifying the nodes to process. Here **//word** specifies all word nodes in the input.
  + **word.list <- xmlApply(word.nodes, xmlToList)** creates a regular R list object from the XML nodeSet object in the input. This step is useful because in enables manipulation of the (formerly XML) data by more familiar base R functions.
    + **xmlApply( )** is a function from the XML package which applies the function argument to each sub-node in the input nodeSet. Here the input nodeSet is **word.nodes** and the function argument is **xmlToList( )**. This function from the XML package generates a "more R-like list" from the appropriate input. 
    + The resulting list object, **word.list** contains a list element for each word node in the input nodeSet. Each list element contains a named character vector with an element for each attribute in the input word node.
  + ** for (j in seq_along(var_names.v)) {...}** is a loop iterating through the number of elements in **var_names.v**. The input **seq_along(var_names.v)** generates the appropriate number of iterations. The loop  creates a data frame object containg one row for each list element in **word.list** and one column for each element in **var.names.v**.
    + **if ( j == 1) {...}** selects code to create the first column of the data frame. It is selected only on the first iteration of the loop (**j == 1**).
    + Note that the following code uses the pipe operator (**%>%**) from the tidyverse package. This command allows more reader-friendly code, since it can be written sequentially rather than as a nested series to be executed from inside out.
      + **base.df <-** assigns the result of the subsequent code to the object named.
        + **word.list %>% map_chr(var_names.v[j])** supplies **word.list** as the input for the function **map_chr( )**. This function (from the tidyverse package) applies its function argument to every element of its input argument and returns a character vector. Here the input is, element by element, the list elements of **word.list**. The argument is the element name provided by **var_names.v[j]**. Since each list element contains a named character vector, using **var_names.v[j]** as the argument returns a character vector of the values of the named element from each word in **word.list.** 
        + **%>% data.frame(check.names = FALSE, stringsAsFactors = FALSE)** pipes the vector into the **data.frame( )** function to create a data frame object of one column and a row number equal to the list items in **word.list.**
    + **else {...}** selects code to create all columns subsequent to the first in the data frame. The code is the same as in the **if** section of the block except that **%>% data.frame(check.names = FALSE, stringsAsFactors = FALSE)** is replaced by
      + **cbind(base.df,  ., stringsAsFactors = FALSE)**. This function adds the piped input as a new column to **base.df.**
  + **colnames(base.df) <- var_names.v** assigns the names of the columns in the data frame **base.df** accoriding to the names of the variables as stored in **var_names.v**. 
  + **new_vars.m <- matrix(nrow = nrow(base.df), ncol = 1)** initializes a matrix object to hold the new combined variables to be generated. The matrix has one column and the same number of rows (1 row per token) as in **base.df**.
  + **nomina <- NULL** initializes an empty vector to hold the names of the new combined variables to be generated.
  + **for (k in seq_along(most_frequent.list)) { ... }** is a loop to create new combined variables. The loop iterates through the number of elements in **most_frequent.list,** which contains names of variables selected by criteria specified elsewhere. The result of the loop is a matrix object with rows for each token in the input **base.df** and columns for each list element in the input **most_frequent.list**. 
    + **var_atoms <- most_frequent.list[[k]]** creates a character vector containing names of variables in **base.df**. The names come from the **kth** list element in **most_frequent.list.**
    + **if (length(var_atoms) > 1) {...}** selects code for vectors containing more than 1 variable name. Such combined variables must be treated differently than simplex variables. 
      + **combined_var <-** creates the data base object and stores in it the result of the following code block
        + **base.df[, var_atoms]** selects a portion of **base.df** containing one row for each row of **base.df** and one column for each variable name in **var_atoms.** The columns contain the values for each row in **base.df** corresponding to the variables whose names are contaied in **var_atoms.**
        + **%>% apply(., 1, paste0, collapse = "/")** pipes the selection from **base.df** as input to the **apply( )** function. This function applies a function argument to all rows or columns of the input argument. Here, the argument **1** indicates that the function is to be applied to rows. **paste0** is the function to be applied; the function joins its input into a single character string made up of the input elements separated by the character specified by the **collapse** argument. The result here is a vector with one character string for each row in the input. This corresponds to a new variable value for each token in the input file.
    + **else {...}** selects code for vectors containing only one variable name.   
      + **combined_var <- base.df[, var_atoms]** creates the data base object and stores in it a portion of **base.df** containing data from all rows of **base.df** from the column indicated by the string in **var_atoms**.
    + **new_vars.m <- cbind(new_vars.m, combined_var)** appends the output of the if...else code block as a column in **new_vars.m**. 
    + **nomina <- append(nomina, paste0(var_atoms, collapse = "_&_"))** populates the vector **nomina** with names for the new variables.
      + **paste0(var_atoms, collapse = "_&_")** makes a single string of the elements in the vector **var_atoms**; the original elements are separated by the string indicated in the **collapse** argument.
      + **append( )** creates a vector by adding its arguments; here to the first argument, **var_atoms,** is added the second argument, the outut of the **paste0( )** function.
  + **new_vars.m <- new_vars.m[, -1]** removes the empty first column from the matrix holding the new variables.
  + **new_vars.m[str_detect(new_vars.m, "NA")] <- NA** replaces the character string "NA" with the logical value NA.  This line uses the function **srt_detect( )** from the stringr package. In this function, the first argument is the input object, the second argument is the character string to be selected. The result is a logical vector with TRUE or FALSE for each element in the input. Here the vector corresponds in length to the number of cells in the matrix **new_vars.m.** The code **new_vars.m[...] <- NA**, wrapped around the **string_detect( )** inserts the logical value NA into each cell for which TRUE is returned by the nested function. **Replacing the character string "NA" with its Boolean counterpart allows these cells to be dropped at a later stage of the process.**
  + **new_vars.m[str_detect(new_vars.m, "NULL")] <- NA** replaces the character string "NULL" with the logical value NA. The code is analogous to the preceding and the purpose is the same.
  + **new_vars.m <-tolower(new_vars.m)** changes all character strings in the matrix to lower case. This step aims to avoid accidental multiplication of variables due to inconsistency of input. The function **tolower( )** is part of base R.
  + **nomina <-  c("token_id", "cite", "form", nomina)** adds three character strings to the front of the **nomina** vector. These strings will be names for columns containing metadata for each token. The **c( )** function (from base R) concatenates its arguments into a single vector in the given order.
  + **file_name <-** creates a vector and assigns it the result of the associated code. The vector will contain the name of the file currently being processed.
    + **files.v[i] %>% gsub(".xml","", .)** removes the ".xml" suffix from the name of the input file as given in **files.v**. **files.v[i]** selects the **ith** element of that vector. The pipe operator sends that element as input to the **gsub( )** function. The **gsub( )** function replaces characters in a string: its first argument is the string to be replaced (here ".xml"). The second argument is the replacement string (here "", indicating the first argument should be dropped with no replacement). The third argument is the input (here a dot indicating that the data from the left of the pipe operator should be used here).
  
      
    

